spring:
  application:
    name: transaction-management
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    driverClassName: org.h2.Driver
    username: ${DB_USER:hsbc}
    password: ${DB_PW:test}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
    context-path: /api

logging:
  level:
    org.springframework.cache: DEBUG